### USER REGISTER

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "marco@gmail.com",
  "password": "admin"
}

### USER LOGIN

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email":"marco@gmail.com",
  "password":"admin"
}

### USER LOGOUT

GET http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: 0.2548523080968996

### USER DELETE

POST  http://localhost:3000/api/user/delete
Content-Type: application/json
Authorization:  0.9665657645650463


{
  "password": "admin"
}




